### ISSUE TITLE
[=BUG=]

### ISSUE THREAD

**Issue by LeRomino** [play-dl/play-dl#207]
input: 'undefined',
  code: 'ERR_INVALID_URL'
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL

**Comment by absidue** [comment]
Please provide more details, in it's current form this issue is useless.

No title, why?
What play-dl version are you using?
What function did you call when the error occurred?
What input did you pass to the function?

Also please provide a full stacktrace by running your code again with `--enable-source-maps` added to your node command. e.g. `node --enable-source-maps ./index.js`.

**Comment by LeRomino** [comment]
play-dl v1.6.0

My code: 
                        try {
                            return (await playdl.stream(track.url)).stream;
                        } catch (err) {
                            return console.log(err);
                        }

**Comment by absidue** [comment]
what is the value of `track.url`?

**Comment by LeRomino** [comment]
track.url = https://www.youtube.com/watch?v=sRaU2uO5qGw

**Comment by absidue** [comment]
Okay so i've fixed the problem, however there is still an issue with that url that i'm trying to solve.

**Comment by LeRomino** [comment]
I will have to update the module?

**Comment by absidue** [comment]
Once a fix is released yes, however as i haven't pushed any changes and there hasn't been a release yet, you still have to wait.

**Comment by LeRomino** [comment]
OK, thank you.

**Comment by killer069** [comment]
@LeRomino 

Hope your issue is fixed.
