### ISSUE TITLE
Streaming from spotify is not supported

### ISSUE THREAD

**Issue by Chinmay-KB** [play-dl/play-dl#210]
#### Describe the bug
When passing a spotify song url, the following error is thrown 
```
Error: Streaming from Spotify is not supported. Please use search() to find a similar track on YouTube or SoundCloud instead.
    at Object.stream (/Users/user/bajao/node_modules/play-dl/dist/index.js:14:2744)
```

 - Node.js version: v17.0.1
 - OS & version: MacOS Monterey

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by absidue** [comment]
This isn't a bug. As stated in the error message, streaming from Spotify is not supported. Due to Spotify's DRM we have no plans to implement streaming from Spotify.

The recommended way to do it, is use the `spotify` function to get the information about the URL, use that to search in YouTube with `search` and use the YouTube URL in the search result with the `stream` function.

**Comment by bootleg-anonymous** [comment]
Same thing applies with Deezer btw^
