### ISSUE TITLE
[=ASK=] Getting Youtube autogenerated playlists doesn't work

### ISSUE THREAD

**Issue by t0maash77** [play-dl/play-dl#220]
#### What would you like to discuss?

Hi, I was wondering if this is a bug or not - if I try to use method `playlist_info()` on playlist which is autogenerated by YT it fails with this errror: `Error: While parsing playlist url
This playlist type is unviewable.`

Example urls which will fail: 
- https://www.youtube.com/watch?v=DHEOF_rcND8&list=RDDHEOF_rcND8&index=1
- https://www.youtube.com/watch?v=kS9uTiEY9ag&list=RDGMEM6ijAnFTG9nX1G-kbWBUCJA&start_radio=1

I see where this is coming from, the url is built here: https://github.com/play-dl/play-dl/blob/e1b0d14477727a3a6010ba894bf21a7ec79b07f1/play-dl/YouTube/utils/extractor.ts#L340
And it tries to look on this url: https://www.youtube.com/playlist?list=RDDHEOF_rcND8 which is unviewable even in the browser.

Is this correct or there might be some change to try to parse the playlist from the original url?

#### Checklist

- [x] I have read the documentation.

**Comment by absidue** [comment]
Auto generated mixes are intentionally not supported at the moment, firstly because they don't count as actual playlists, which means the videos they contain are different for each user and secondly because they aren't actual playlists, they don't have a dedicated playlist page.

So yes support could be added, however it may end up being completely useless to you, as YouTube will generate a completely different "playlist" for your bot than what you see in the app or on the website.

**Comment by killer069** [comment]
This fix is ready in the pr.

So will be fixed with next update
