### ISSUE TITLE
[=FEATURE=] Array argument in video_basic_info() and video_info()

### ISSUE THREAD

**Issue by Unaty498** [play-dl/play-dl#236]
#### What problem are you trying to solve?
Hey, I was wondering if it would be possible to implement that, because it would be really useful when displaying queues, to avoid having to do multiple requests...

#### Describe the feature

Add the possibility to use video_info and video_basic_info with an array of URLs or IDs

**Comment by absidue** [comment]
Hi
Because play-dl scrapes the information from the website and doesn't use the official YouTube API, there is no way to avoid having to make multiple requests to YouTube. So the way it would be implemented in play-dl would be no more efficient or different from calling `video_info` or `video_basic_info` multiple times from your own code.

**Comment by Unaty498** [comment]
Oh ok then, have a great day !
