### ISSUE TITLE
[=BUG=] play.spotify not working

### ISSUE THREAD

**Issue by retrouser955** [play-dl/play-dl#313]
#### Describe the bug

 - Node.js version: v18.6.0
 - OS & version: windows 10 home

I was going to implement Spotify with my bot but I ran into an error. The error is the following

TypeError: Cannot read properties of undefined (reading 'spotify')

The code that the error originated from

node_modules\play-dl\dist\index.js:7:23373

#### Expected behavior

Returns the Spotify data based on the Spotify URL

#### Code to reproduce

```js
(async () => {
    const play = require('play-dl')
    await play.setToken({
        spotify: {
            client_id: 'Your client ID',
            client_secret: 'Your client secret'
        }
    })
    const spotifyData = await play.spotify('https://open.spotify.com/track/68EkhVWIeULhHxcbi1QhzK?si=552afb7974a24417')
    console.log(spotifyData)
})()
```

#### ScreenShots
![image](https://user-images.githubusercontent.com/70205403/180918982-f0409fd3-85c7-4630-9550-75c6a58364a8.png)

![image](https://user-images.githubusercontent.com/70205403/180919048-5b30ce81-d966-4fe4-91d2-d4b9d1fdd35a.png)

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by AtariTom** [comment]
`setToken` requires more info for the spotify requests to work properly. You're currently receiving an error because you're missing some credentials. Make sure you pass the market (two letter country code) and refresh token into the `setToken` function along with your client ID and secret.
You can follow the [spotify instructions](https://github.com/play-dl/play-dl/tree/main/instructions#spotify) to get the refresh token if you don't know how.

**Comment by retrouser955** [comment]
Thank you!
